FROM python:3.8

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Prague

RUN apt-get update \
    && apt-get install -y libxml2 g++ vim coreutils nano git libxrender1 wget fakeroot tzdata locales nginx parallel \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN ln -fs /usr/share/zoneinfo/Europe/Prague /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen

RUN addgroup --gid 1000 user \
    && adduser --gid 1000 --uid 1000 --disabled-password --gecos "user" user
WORKDIR /home/user

RUN mkdir -p /var/lib/nginx/body /var/lib/nginx/fastcgi /var/lib/nginx/proxy /var/lib/nginx/uwsgi /var/lib/nginx/scgi \
    && chown -R user:user /var/lib/nginx \
    && chmod 755 /home /var/lib/nginx \
    && touch /var/log/nginx/access.log /var/log/nginx/error.log \
    && chown -R user:user /var/log/nginx/access.log /var/log/nginx/error.log \
    && chmod 644 /var/log/nginx/access.log /var/log/nginx/error.log \
    && touch /run/nginx.pid \
    && chown -R user:user /run/nginx.pid

COPY ./api/requirements.txt .
RUN pip install --upgrade pip \
    && pip install torch --index-url https://download.pytorch.org/whl/cu118 \
    && pip install -r requirements.txt \
    && rm -rf ~/.cache

COPY ./api/server/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./api/server/init.sh .
COPY ./api/usalign ./usalign
COPY ./api/prep ./prep
COPY ./training/data ./data

RUN python prep/prepare-proteins-index.py \
    && chown -R user:user /home/user

EXPOSE 8000
USER 1000

CMD [ "/home/user/init.sh" ]
